### ISSUE TITLE
`t` parameter in url

### ISSUE THREAD

**Issue by witkwski** [ElMassimo/vite_ruby#102]
hey @ElMassimo !

[here](https://github.com/ElMassimo/vite_ruby/blob/a964452902eefa67f11a3483dcbc01590eb51e6a/vite_ruby/lib/vite_ruby/dev_server_proxy.rb#L55) the engine checks for `t=` parameter and seems like it interrupts all requests with such parameter

for example `localhost:3000/whatever?t=1` - it tries to handle such link, even if `whatever` resource is defined in the routes

prob some additional conditions should be added while looking for the param or it's the key part of the mechanics?
thanks!

**Comment by ElMassimo** [comment]
Hi Anton, thanks for reporting.

This is a known issue. Under some circumstances such as when Hot Reloading a stylesheet, Vite will issue requests without the expected prefix, making it difficult to verify whether it should be proxied or not.

Planning to revisit the proxy implementation soon in order to provide better error messages.

I'll use that opportunity to check whether a different workaround can be used for stylesheets HMR so that it doesn't interfere with non-Vite requests.

**Comment by ElMassimo** [comment]
@witkwski I've released a [new version](https://rubygems.org/gems/vite_ruby/versions/1.2.18.pre.rc1) of `vite_ruby` with a more robust proxy strategy.

I'd like to test it in my projects for a few days to make sure it doesn't introduce any regressions to HMR, which is tricky to cover in the tests.

Feel free to upgrade using `gem 'vite_ruby', '1.2.18.pre.rc1'`.

**Comment by pocheptsov** [comment]
Thank you @ElMassimo it's very useful!

**Comment by witkwski** [comment]
@ElMassimo excellent! thank you much

**Comment by ElMassimo** [comment]
[`vite_ruby@1.2.18`](https://rubygems.org/gems/vite_ruby/versions/1.2.18) is now available, which fixes this issue.

Thanks again for the report @witkwski
