### ISSUE TITLE
Support for inferred `index` entrypoints

### ISSUE THREAD

**Issue by sionzee** [ElMassimo/vite_ruby#105]
**Is your feature request related to a problem? Please describe.**
The current implementation allows to place entrypoints to root of `entrypointsDir` but all other directories inside `entrypointsDir` are ignored. At our project we have hierarchy structure for entries and then we are referencing the path at pack_tag.

For example:
```
frontend
  - entrypoints
    - application.ts
    - features
      - feature_a
        - index.ts
      - feature_b
        - index.ts
      - feature_c
        - index.ts
```

Then in .html.erb files:

```erb
<%= vite_typescript_tag 'features/feature_a' %>
<%= vite_typescript_tag 'features/feature_c' %>
```

**Describe the solution you'd like**
The current implementation should be edited to support nested directories in entrypoints directory and detect for index.ts files. Actually webpacker supports nested directories but doesn't look for index.ts.

With the index.(ts,js) lookup we can simplify the import from
```erb
<%= vite_typescript_tag 'features/feature_a/index' %>
```
to
```erb
<%= vite_typescript_tag 'features/feature_a' %>
```

So the behavior will be more consistent with `vite` and other bundlers which are auto-detecting the `index` file too.

---
Adding info about used libraries and versions

packages:
```
"vite": "^2.4.2",
"vite-plugin-ruby": "^2.0.4"
```
gem:
```
gem 'vite_rails'
gem 'rails', '6.1.3.2'
```

**Comment by ElMassimo** [comment]
Hi Jan!

> but all other directories inside entrypointsDir are ignored.

This is not correct—currently any entrypoints in nested directories can be referenced.

Example: `<%= vite_typescript_tag 'features/feature_a/index' %>`

If you are still running into problems after explicitly adding `/index`, please share a reproduction and we can reopen this 😃 

<hr>

> The current implementation should be edited to detect for index.ts

Auto-detecting `index` files would imply performing several filesystem checks, since a file could have different file extensions, such as `.js` and `.ts`. Adding it for scripts would make a user expect the same behavior in stylesheet helpers, which can have extensions such as `.css`, `.scss`, `.less`, and so on.

These filesystem checks would need to be performed for __every__ request made to the Rails server in development.

I don't think it's worth introducing this additional complexity if the sole purpose is skipping `/index` when using helper tags. If there are other reasons to prefer this approach, please share them and I'll reconsider it.
