### ISSUE TITLE
vite-ruby breaks tailwindcss jit mode

### ISSUE THREAD

**Issue by grk** [ElMassimo/vite_ruby#114]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x] I have tried upgrading by running `bundle update vite_ruby`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

vite-ruby dev server seems to be not compatible with tailwindcss jit mode. Adding new classes that should trigger new CSS to be emitted does not do that, resulting in unstyled elements until dev server is restarted. It works fine when building on reload without dev server running.

### Reproduction 🐞

https://github.com/grk/rails-vite-tailwind-repro - instructions in readme

<details>
<summary>Vite Ruby Info</summary>

_Run `bin/rake vite:info` and provide the output:_

```
bin/vite present?: true
vite_ruby: 1.2.20
vite_rails: 2.0.13
rails: 6.1.4
node: v16.1.0
npm: 7.11.2
yarn: 1.22.10
pnpm:
ruby: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [arm64-darwin20]

installed packages:
rails-vite-tailwind-repro@ /Users/grk/code/tmp/rails-vite-tailwind-repro
├─┬ vite-plugin-ruby@2.0.5
│ └── vite@2.4.4 deduped
└── vite@2.4.4
```
</details>

### Logs 📜

_If not providing a reproduction:_

<details>
<summary>Output</summary>

_Run `DEBUG=vite-plugin-ruby:* bin/vite dev` or `DEBUG=vite-plugin-ruby:* bin/vite build` and provide the output:_

```

```
</details>

### Screenshots 📷

_Provide console or browser screenshots of the problem_.

**Comment by ElMassimo** [comment]
Hi Grzesiek, thanks for reporting.

Since files are being scanned correctly during startup, it's likely to be a bug in the watcher or the dependencies that Tailwind sets up in JIT mode.

Notice how Vite.js does not include an update for `index.css`, only the component is invalidated:

<img width="1440" alt="Screen Shot 2021-08-11 at 18 20 34" src="https://user-images.githubusercontent.com/1158253/129105035-5ba71554-91b7-48e4-aa61-fbbe1753e2ea.png">

When the watcher detects changes as expected, that same message would include an `update` for `index.css`, which is the file where the Tailwind CSS styles are injected.

Since the problem does not occur within the gem or `vite-plugin-ruby`, I'm afraid I don't have a way to resolve this bug report.

JIT mode is experimental, I'd recommend that you ask for help in a Tailwind forum, or report the bug in the Tailwind tracker.
