### ISSUE TITLE
MissingEntrypointError logs can get really long

### ISSUE THREAD

**Issue by GabrielMahan** [ElMassimo/vite_ruby#127]
https://github.com/ElMassimo/vite_ruby/blob/97e7e966a2c65c89e3e2bef41772b9f87cd444ca/vite_ruby/lib/vite_ruby/missing_entrypoint_error.rb#L19

This is a pretty minor point, but for large projects printing out the entire manifest can be a little overwhelming, especially if one is doing something like saving test output from acceptance tests.

There could be a lot of possible solutions, eg:
+ only print if the manifest text is under a certain line-count
+ only list entrypoints or entrypoints that meet some sort of matching criteria
+ something else? 

Or maybe this isn't a big enough deal to address...

@ElMassimo I'd be happy to make a contribution if you think it'd be useful!

**Comment by ElMassimo** [comment]
Since this error would typically result in a runtime error during production, it's usually desirable that it provides as much information as possible.

You could monkey patch the [exception message](https://github.com/ElMassimo/vite_ruby/blob/0850af2170077bd55d54a725fa6030a32bbbd401/vite_ruby/lib/vite_ruby/missing_entrypoint_error.rb#L7) in the __test__ environment and customize it as desired.
