### ISSUE TITLE
"can't detect preamble" error with React plugin

### ISSUE THREAD

**Issue by mdesantis** [ElMassimo/vite_ruby#153]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x] I have tried upgrading by running `bundle update vite_ruby`.
- [x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

Hello! I'm playing with Vite Rails, trying to create a Vite Rails + React demo app. The problem is that I'm getting the following error:

```
Uncaught Error: @vitejs/plugin-react can't detect preamble. Something is wrong. See https://github.com/vitejs/vite-plugin-react/pull/11#discussion_r430879201
```

[The error is reported in the readme of VIte Rails plugin](https://github.com/vitejs/vite/blob/e1d82fc853e67943faa395b9b4ff0575cf614bd0/packages/plugin-react/README.md#middleware-mode), suggesting that:

> In middleware mode, you should make sure your entry index.html file is transformed by Vite

But frankly I know nothing about Vite so my debugging stopped here :D

### Reproduction 🐞

1. Clone the folowing repository: https://github.com/mdesantis/rails-7-demo-vite
2. `bin/setup`
3. `foreman start -f Procfile.dev`
4. visit `http://localhost:5100/hello_react`

<details>
<summary>Vite Ruby Info</summary>

_Run `bin/rake vite:info` and provide the output:_

```
bin/vite present?: true
vite_ruby: 3.0.3
vite_rails: 3.0.1
rails: 7.0.0.rc1
node: v14.17.5
npm: 8.0.0
yarn: 1.22.15
pnpm: 
ruby: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]

installed packages:
rails-7-demo-vite@ /home/maurizio/Sviluppo/rails-7/rails-7-demo-vite
├─┬ vite-plugin-ruby@3.0.4
│ └── vite@2.7.1 deduped
└── vite@2.7.1
```
</details>

### Screenshots 📷

![Schermata del 2021-12-10 00-09-23](https://user-images.githubusercontent.com/283320/145490108-47d7429f-0be8-43f0-aaac-8617fe5426f3.png)

**Comment by ElMassimo** [comment]
[As mentioned in the Troubleshooting section](https://vite-ruby.netlify.app/guide/troubleshooting.html#hot-module-refresh-does-not-work-for-react), when using Vite Ruby the entrypoints are JS files and stylesheets instead of an `index.html` file, it's necessary to [add the preamble manually](https://vite-ruby.netlify.app/guide/rails.html#enabling-hot-module-reload-%F0%9F%94%A5) when using `@vitejs/plugin-react`.

To make the integration simpler, Vite Ruby provides a [`vite_react_refresh_tag` to inject the preamble](https://vite-ruby.netlify.app/guide/rails.html#enabling-hot-module-reload-%F0%9F%94%A5), which you should place in your [layout](https://github.com/ElMassimo/vite_ruby/blob/main/examples/rails/app/views/layouts/application.html.erb#L8).

I might asd

**Comment by mdesantis** [comment]
@ElMassimo got it, I didn't notice that section of the guide. Thanks!
