### ISSUE TITLE
MissingExecutableError when deploying with Capistrano

### ISSUE THREAD

**Issue by octave** [ElMassimo/vite_ruby#192]
Hi,

I get this error at `rake assets:precompile`  when deploying with Capistrano. It looks like it's not doing a `yarn install` first?

```
$HOME/.rbenv/bin/rbenv exec bundle exec rake assets:precompile
      01 Building with Vite ⚡️
      01 rake aborted!
      01 ViteRuby::MissingExecutableError: ❌ The vite binary is not available. Have you installed the npm packages?
      01
      01 Visit the Troubleshooting guide for more information:
      01   https://vite-ruby.netlify.app/guide/troubleshooting.html#troubleshooting
      01
      01 No such file or directory - /$HOME/node_modules/.bin/vite
```

**Comment by ElMassimo** [comment]
Hi Octave! Thanks for reporting 😃 

Vite Ruby [will install dependencies](https://github.com/ElMassimo/vite_ruby/blob/main/vite_ruby/lib/tasks/vite.rake#L50) if `assets:precompile` was not defined, otherwise it assumes that `webpacker` or `sprockets` would, and __skips it to avoid running install twice__.

This assumption has changed given all the recent activity in the Rails ecosystem (for example, replacing sprockets with propshaft).

Please share a minimal reproduction with the gems in the application that [define the `assets:precompile` task before Vite Ruby does](https://github.com/ElMassimo/vite_ruby/blob/main/vite_ruby/lib/tasks/vite.rake#L44) in a way that does not install dependencies.

That way we can gather more information about specific gems that might need to be taken into account in order to extend `assets:precompile` as needed.

**Comment by octave** [comment]
Hi @ElMassimo!

No worries! I generated my rails app with the `--minimal` parameter. And so my Gemfile currently look like this:

```
ruby "3.1.0"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.2", ">= 7.0.2.2"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

gem 'turbo-rails'

gem 'vite_rails'
```

If you add `--css=bootstrap` when generating your app it adds the gem `cssbundling-rails` which trig `yarn install` when running `assets:precompile`

The workaround I found for now, is to use the gem `capistrano-yarn` and in the capistrano `production.rb` I configure it like this: `set :yarn_flags, '--development'`.

**Comment by ElMassimo** [comment]
I think it might be reasonable to extend `assets:precompile` with `vite:install_dependencies` if `webpacker`, `cssbundling-rails`, and `jsbundling-rails` are not in the loaded gems.

For now, as a workaround, you can do:

```ruby
Rake::Task['assets:precompile'].enhance(['vite:install_dependencies'])
```
