### ISSUE TITLE
Rails Capistrano deploys breaking due to manifest-assets.json 

### ISSUE THREAD

**Issue by dmix** [ElMassimo/vite_ruby#204]
Our app was deploying fine until we upgrade vite_ruby to 3.1.0.

Specifically this commit added an additional `manifest-assets.json` file (in addition to `manifest.json`):

https://github.com/ElMassimo/vite_ruby/commit/d5704ab55abf27cbdb5b00841bce3136147a020

But this is causing our deploys to fail because Capistrano does a `wc -l manifest*` check due to Rails 3 -> Rails 4 upgrade check:

<img width="1481" alt="Screen Shot 2022-04-17 at 6 03 43 PM" src="https://user-images.githubusercontent.com/12528/163733780-ef34d1e5-82d2-4f43-a91c-103940f7499e.png">

You can see how Capistrano checks for this "duplicate" manifest file in their source code:

```
if capture("ls -1 #{shared_path.shellescape}/#{shared_assets_prefix}/#{asset_manifest_prefix}* | wc -l").to_i > 1
  raise "More than one asset manifest file was found in '#{shared_path.shellescape}/#{shared_assets_prefix}'.  If you are upgrading a Rails 3 application to Rails 4, follow these instructions: http://github.com/capistrano/capistrano/wiki/Upgrading-to-Rails-4#asset-pipeline"
end
```
https://github.com/capistrano/capistrano/blob/legacy-v2/lib/capistrano/recipes/deploy/assets.rb#L69

The only way I could get deploys to work again was to manually delete `manifest-assets.json` (or downgrade vite_ruby). 

Not sure how to proceed here given the filename for manifest-assets is hardcoded in the current library.

**Comment by ElMassimo** [comment]
Hi Daniel!

[That commit](https://github.com/ElMassimo/vite_ruby/commit/d5704ab55abf27cbdb5b00841bce3136147a020) did not add `manifest-assets.json`, it only documents that it should be tracked by Capistrano.

[`manifest-assets.json` has been used since before Vite 2 was released](https://github.com/ElMassimo/vite_ruby/pull/8).

You seem to be using an [outdated](https://github.com/capistrano/capistrano/blob/legacy-v2/lib/capistrano/recipes/deploy/assets.rb#L69) version of Capistrano.

That warning is no longer present in Capistrano 3, for which you would use `capistrano-rails`.
