### ISSUE TITLE
host 0.0.0.0 doesn't set ViteRuby.instance.dev_server_running? to true

### ISSUE THREAD

**Issue by Jaroost** [ElMassimo/vite_ruby#206]
### Description 📖
When host is set to 0.0.0.0 in config/vite.json `ViteRuby.instance.dev_server_running?` is set to `false `because  of this line : `Socket.tcp(config.host, config.port, connect_timeout: config.dev_server_connect_timeout).close` trying to connect to 0.0.0.0

### Reproduction 🐞

Platform: Windows
vite.json:

```
{
  "all": {
    "sourceCodeDir": "app/javascript/",
    "watchAdditionalPaths": []
  },
  "development": {
    "autoBuild": true,
    "publicOutputDir": "vite-dev",
    "port": 3035,
    "https": true,
    "host": "0.0.0.0"
  },
  "test": {
    "autoBuild": true,
    "publicOutputDir": "vite-test",
    "port": 3037
  }
}
```

when starting vite/dev:

```
  vite v2.9.1 dev server running at:

  > Network:  https://10.20.11.53:3035/vite-dev/
  > Network:  https://192.168.56.1:3035/vite-dev/
  > Network:  https://192.168.8.1:3035/vite-dev/
  > Local:    https://localhost:3035/vite-dev/

  ready in 2100ms.
```

In ruby server, check `ViteRuby.instance.dev_server_running?` it shall be `false `

**Comment by ElMassimo** [comment]
Hi Antoine!

This problem is related to the [local resolution of the `0.0.0.0` IP address](https://vite-ruby.netlify.app/guide/troubleshooting.html#requests-to-vite-refuse-to-connect-for-1).

In systems that can resolve `0.0.0.0` correctly, it works as expected:

```ruby
irb(main):003:0> ViteRuby.config.host
=> "0.0.0.0"
irb(main):004:0> ViteRuby.instance.dev_server_running?
=> true
```

You can configure your system to resolve that address, or as a workaround, specify [`server.host`](https://vitejs.dev/config/#server-host) in your `vite.config.ts` file instead.
