### ISSUE TITLE
Environment Variables are not being loaded in the latest release

### ISSUE THREAD

**Issue by adenta** [ElMassimo/vite_ruby#214]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [ x] I have tried upgrading by running `bundle update vite_ruby`.
- [x ] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

When I run this app locally, the `.env` variables are not being picked up. Run the app and look at the console where im logging `import.meta.env` and `VITE_FOO` isn't showing up.

### Reproduction 🐞

[[_Please provide a link to a repo that can reproduce the problem you ran into._
](https://github.com/adenta/vite-env-not-working-example)](https://github.com/adenta/vite-env-not-working-example)

<details>
<summary>Vite Ruby Info</summary>

_Run `bin/rake vite:info` and provide the output:_

```

```
</details>

### Logs 📜

_If not providing a reproduction:_

<details>
<summary>Output</summary>

_Run `DEBUG=vite-plugin-ruby:* bin/vite dev` or `DEBUG=vite-plugin-ruby:* bin/vite build` and provide the output:_

```

```
</details>

### Screenshots 📷

_Provide console or browser screenshots of the problem_.

**Comment by ElMassimo** [comment]
Hi Andrew, thanks for reporting!

This behavior is due to [a change in Vite 2.9 which sets `envDir` to match the root](https://github.com/vitejs/vite/blob/main/packages/vite/CHANGELOG.md#envdir-changes).

When using Vite Ruby the `root` is [`sourceCodeDir`](https://vite-ruby.netlify.app/config/index.html#sourcecodedir) (`app/frontend`).

I think it would make sense for `vite-plugin-ruby` to explicitly set [`envDir`](https://vitejs.dev/config/#envdir) to the Rails root (`projectRoot`), which was the behavior in Vite pre 2.9, pull requests are welcome!

In the meantime, you can explicitly set [`envDir`](https://vitejs.dev/config/#envdir) manually.

**Comment by adenta** [comment]
Setting the `envDir` to  "../../" does indeed resolve my issue. 

Will this _just work_:tm: in production?

**Comment by ElMassimo** [comment]
Yes, it would 😄 

Released [`vite-plugin-ruby@3.0.12`](https://github.com/ElMassimo/vite_ruby/blob/main/vite-plugin-ruby/CHANGELOG.md#3012-2022-05-15) which uses an absolute path instead of `../../`.

**Comment by devsheva** [comment]
Hi, I have the same problem now. I saw from https://vite-ruby.netlify.app/config/#root that `root` is set to `Rails.root`.
I have my `.env` & `.env.local` files under `app/frontend`, but they're not getting picked by vite

**Comment by devsheva** [comment]
seems working with this config, so actually setting `envDir` to `.` works, but it's "strange" in my opinion.
```js
import react from '@vitejs/plugin-react'

import ViteYaml from '@modyfi/vite-plugin-yaml'
import {resolve} from 'path'
import { defineConfig } from 'vite'
import Rails from 'vite-plugin-rails'

export default defineConfig({
  resolve: {
    alias: {
      '@locales': resolve('config/locales'),
      '@enums': resolve('lib/enums')
    },
  },
envDir: '.',
  plugins: [
    react(),
    ViteYaml(),
    Rails({
      fullReload: {
        additionalPaths: ['config/locales/**'],
        delay: 200,
      },
    }),
  ],
})

```
