### ISSUE TITLE
assets:precompile works when yarn is available but npx is not

### ISSUE THREAD

**Issue by joekrump** [ElMassimo/vite_ruby#342]
**Is your feature request related to a problem? Please describe.**

On Heroku, `rails assets:precompile` fails if only using [the Ruby buildpack](https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-ruby), because npm is not installed, and therefore `npx --yes ci` fails silently because `npx` is not installed. 

This ends up leading to a failure when attempting to run vite because it is not found.

**Describe the solution you'd like**

It would be nice if in an environment where `yarn` is available, run `yarn install --frozen-lockfile` instead of `npx --yes ci` to remove the dependency on npx.

**Describe alternatives you've considered**

Another solution is to use the Heroku node buildpack in conjunction with the ruby since as part of that, `yarn install` gets run. This would result in `vite` being available so even if `npx --yes ci` fails, dependencies (including vite) will be installed.

**Additional context**

The error I get on Heroku:

<img width="683" alt="image" src="https://user-images.githubusercontent.com/3317231/222213711-742d328a-a1e5-4813-a567-ff39dc7de2b4.png">

**Comment by ElMassimo** [comment]
Hi Joe!

> Another solution is to use the Heroku node buildpack in conjunction with the ruby 

That's the [recommended deployment setup for Heroku](https://vite-ruby.netlify.app/guide/deployment.html#using-heroku), and would also allow you to use whatever package manager you prefer (instead of being forced to use `yarn`).

However, given how simple it is to detect whether `npx` is not available, and given how `yarn` was for a very long time the only package manager "blessed" by Rails, falling back to `yarn install --frozen-lockfile` sounds reasonable.

**Comment by joekrump** [comment]
Thank you @ElMassimo !
