### ISSUE TITLE
Ruby 3.4 ostruct warning

### ISSUE THREAD

**Issue by mattbrictson** [ElMassimo/vite_ruby#489]
### Description 📖

ViteRuby requires `ostruct`, but doesn't declare it as a gemspec dependency. This causes a warning to be printed in Ruby 3.4.

### Reproduction 🐞

Run the following script using Ruby 3.4.0-preview1:

```ruby
require "bundler/inline"
gemfile do
  source "https://rubygems.org"
  gem "vite_ruby"
end
ViteRuby::Manifest
```

> warning: ostruct was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.5.0. Add ostruct to your Gemfile or gemspec.

### Expectation

`ostruct` should be added to the ViteRuby gemspec, or the code should be refactored to remove the use of `OpenStruct`.

**Comment by ElMassimo** [comment]
Hi Matt! Thanks for reporting.

Given it's only used for `MissingEntrypointError`, I think we can skip the dependency and refactor [this](https://github.com/ElMassimo/vite_ruby/blob/main/vite_ruby/lib/vite_ruby/manifest.rb#L217) to:

```ruby
    raise ViteRuby::MissingEntrypointError.new(
      file_name: resolve_entry_name(name, **options),
      last_build: builder.last_build_metadata,
      manifest: @manifest,
      config: config,
    )
```

modifying the [`initialize` method](https://github.com/ElMassimo/vite_ruby/blob/main/vite_ruby/lib/vite_ruby/missing_entrypoint_error.rb#L11) to receive keywords instead, and manually assign these four instance variables instead of delegating to `@info`.
