### ISSUE TITLE
Support for Rails 4.2

### ISSUE THREAD

**Issue by CyberAP** [ElMassimo/vite_ruby#9]
**Is your feature request related to a problem? Please describe.**
Thanks for the great plugin for Rails and Vite, unfortunately I am unable to use it on my project since the plugin requires Rails 5.1 and higher, but I am stuck with 4.2 and can not do anything about it.

**Describe the solution you'd like**
Is there anything that could be done here? Is it possible to add support for older versions of Rails, specifically 4.2? Webpacker has it supported and I would like to migrate from Webpacker to Vite with this plugin but without upgrading Rails. Any help would be much appreciated, thanks!

**Comment by ElMassimo** [comment]
Hi Stanislav!

The main reason I have not added support for versions earlier than `5.1` is to simplify maintenance.

The following assumptions this library makes no longer hold when in `4.2`:

- <kbd>assets:precompile</kbd> depends on <kbd>yarn:install</kbd> (this was added in later versions)
- `rails app:template` is a valid command (`rake rails:template` in older versions)
- `app.middleware.insert_before` can receive a class (should be a string in older versions)

If folks have enough interest in using this library in `4.2`, it would be reasonable to support it if the impact is reduced to the list above.

Otherwise, it might be better to create a `4.2` only fork with the necessary changes (and reuse the same `vite-plugin-ruby` JS package). If the changes are small I'll consider merging it 😃

**Comment by ElMassimo** [comment]
@CyberAP Created `vite_rails_legacy` in #13.

I won't support it, but feel free to give it a try.
