### ISSUE TITLE
Assets not minifying for production

### ISSUE THREAD

**Issue by damwhit** [ElMassimo/vite_ruby#91]
[troubleshooting section]: https://vite-ruby.netlify.app/guide/troubleshooting.html

- [x] I have read the __[troubleshooting section]__ before opening an issue.

### Description 📖

First off, thanks for putting this project together. It's such an improvement on webpacker regarding its ease of use and configuration.

I'm deploying a dockerized rails app to heroku and followed the instructions in the docs site for a heroku deploy. I also confirmed that the `vite:build` command is running when the `assets:precompile` command runs. 

I feel like there is something simple that I'm missing, but when I look at the source code for my deployed app, all of the js not minified and the tree structure is in tact (screenshot comparison below between the sample deployed app on the docs site and my deployed app).

### Reproduction 🐞

https://github.com/damwhit/harvest_helper/tree/vite-vue

### Screenshots 📷

<img width="751" alt="Screen Shot 2021-06-10 at 2 26 08 PM" src="https://user-images.githubusercontent.com/13105577/121578218-706a0200-c9f8-11eb-98b6-b55c220c0e12.png">

<img width="765" alt="Screen Shot 2021-06-10 at 2 26 00 PM" src="https://user-images.githubusercontent.com/13105577/121578235-75c74c80-c9f8-11eb-96fe-c6b83d253f34.png">

Thanks for your help!

**Comment by ElMassimo** [comment]
Hi David!

The `.vue` component that you are seeing is being obtained by the browser through the sourcemaps, since you are inspecting the app in _DevTools_.

<img width="1074" alt="HarvestHelper" src="https://user-images.githubusercontent.com/1158253/121581851-b6c55e00-ca04-11eb-97f7-d00ecbd00ba8.png">

If you click the _(source mapped from ...)_ link, it will open the JS file being used on the page, and if you pretty-print the file you should be able to find your compiled Vue components:

<img width="921" alt="HarvestHelper" src="https://user-images.githubusercontent.com/1158253/121582302-36ebc380-ca05-11eb-88d8-09b99ddb70e0.png">

The [sourcemaps](https://vite-ruby.netlify.app/config/#source-maps-%F0%9F%97%BA) are only fetched if you open DevTools, so don't worry about performance. They are very helpful because you can set breakpoints on the original sources, as well as get the exact line where an error occurred if you are using a [bug tracker](https://github.com/ElMassimo/vite-plugin-bugsnag).
